// Datos de demostración para arrancar la app sin Supabase configurado.
import type {
  Cliente,
  Prenda,
  Empeno,
  MovimientoCaja,
} from "@/lib/types";

const dias = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
};
const ahora = (n = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
};

export const clientesSeed: Cliente[] = [
  {
    id: "c1",
    nombre: "María",
    apellidoPaterno: "González",
    apellidoMaterno: "Ramírez",
    curp: "GORM850312MDFLMR04",
    rfc: "GORM850312AB1",
    telefono: "55 1234 5678",
    email: "maria.gonzalez@example.com",
    tipoIdentificacion: "INE",
    numeroIdentificacion: "IDMEX1234567890",
    direccion: "Av. Insurgentes Sur 1234, Col. Del Valle, CDMX",
    fechaNacimiento: "1985-03-12",
    notas: null,
    creadoEn: ahora(-40),
  },
  {
    id: "c2",
    nombre: "Juan Carlos",
    apellidoPaterno: "Hernández",
    apellidoMaterno: "López",
    curp: "HELJ900721HDFRPN09",
    rfc: null,
    telefono: "55 9876 5432",
    email: null,
    tipoIdentificacion: "Licencia",
    numeroIdentificacion: "DF0987654321",
    direccion: "Calle Morelos 56, Centro, Toluca",
    fechaNacimiento: "1990-07-21",
    notas: "Cliente frecuente.",
    creadoEn: ahora(-25),
  },
  {
    id: "c3",
    nombre: "Ana Sofía",
    apellidoPaterno: "Martínez",
    apellidoMaterno: "Cruz",
    curp: "MACA920518MMCRRN02",
    rfc: null,
    telefono: "722 555 1212",
    email: "ana.martinez@example.com",
    tipoIdentificacion: "Pasaporte",
    numeroIdentificacion: "G12345678",
    direccion: null,
    fechaNacimiento: "1992-05-18",
    notas: null,
    creadoEn: ahora(-10),
  },
];

export const prendasSeed: Prenda[] = [
  {
    id: "p1",
    folio: "PR-0001",
    categoria: "Joyería",
    descripcion: "Anillo de oro con incrustación",
    marca: null,
    modelo: null,
    serie: null,
    metal: "Oro",
    kilataje: "14k",
    gramos: 8.5,
    valorAvaluo: 6800,
    montoPrestamoSugerido: 3400,
    estado: "empenada",
    fotos: [],
    notas: "Peso verificado en báscula calibrada.",
    creadoEn: ahora(-40),
  },
  {
    id: "p2",
    folio: "PR-0002",
    categoria: "Electrónica",
    descripcion: 'Laptop 14" 16GB RAM',
    marca: "Dell",
    modelo: "Inspiron 14",
    serie: "SN-DLL-99821",
    metal: null,
    kilataje: null,
    gramos: null,
    valorAvaluo: 9000,
    montoPrestamoSugerido: 4500,
    estado: "empenada",
    fotos: [],
    notas: null,
    creadoEn: ahora(-25),
  },
  {
    id: "p3",
    folio: "PR-0003",
    categoria: "Relojes",
    descripcion: "Reloj automático acero inoxidable",
    marca: "Seiko",
    modelo: "5 Sports",
    serie: "SK-5599",
    metal: null,
    kilataje: null,
    gramos: null,
    valorAvaluo: 4200,
    montoPrestamoSugerido: 2100,
    estado: "en_avaluo",
    fotos: [],
    notas: null,
    creadoEn: ahora(-2),
  },
];

export const empenosSeed: Empeno[] = [
  {
    id: "e1",
    folio: "EM-0001",
    clienteId: "c1",
    prendaId: "p1",
    montoPrestado: 3400,
    tasaInteres: 15,
    periodo: "mensual",
    plazoPeriodos: 1,
    fechaInicio: dias(-40),
    fechaVencimiento: dias(-10),
    diasGracia: 7,
    estado: "vencido",
    notas: null,
    creadoEn: ahora(-40),
  },
  {
    id: "e2",
    folio: "EM-0002",
    clienteId: "c2",
    prendaId: "p2",
    montoPrestado: 4500,
    tasaInteres: 12,
    periodo: "mensual",
    plazoPeriodos: 1,
    fechaInicio: dias(-25),
    fechaVencimiento: dias(5),
    diasGracia: 7,
    estado: "activo",
    notas: null,
    creadoEn: ahora(-25),
  },
];

export const movimientosSeed: MovimientoCaja[] = [
  {
    id: "m0",
    fecha: ahora(0),
    tipo: "apertura",
    monto: 20000,
    esEntrada: true,
    concepto: "Apertura de caja",
    empenoId: null,
    referencia: null,
    creadoEn: ahora(0),
  },
  {
    id: "m1",
    fecha: ahora(-40),
    tipo: "prestamo",
    monto: 3400,
    esEntrada: false,
    concepto: "Préstamo empeño EM-0001",
    empenoId: "e1",
    referencia: "EM-0001",
    creadoEn: ahora(-40),
  },
  {
    id: "m2",
    fecha: ahora(-25),
    tipo: "prestamo",
    monto: 4500,
    esEntrada: false,
    concepto: "Préstamo empeño EM-0002",
    empenoId: "e2",
    referencia: "EM-0002",
    creadoEn: ahora(-25),
  },
];
